// Generated by CoffeeScript 1.10.0
var RAND_1k, RAND_20, SMALL_5, TECH_30k, TSP_225, ctx, cvs, n, points, rescale, scale, setScale, small_5_points, sx, sy, tsp_225_points, type, updateVis;

cvs = null;

ctx = null;

window.addEventListener("load", function() {
  cvs = document.getElementById("canvas");
  ctx = cvs.getContext("2d");
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, 500, 500);
  return updateVis();
});

SMALL_5 = 0;

RAND_20 = 1;

TSP_225 = 2;

RAND_1k = 3;

TECH_30k = 4;

n = 30000;

type = TECH_30k;

small_5_points = [];

tsp_225_points = [];

points = [small_5_points, rand_20_points, tsp_225_points, rand_1k_points, tech_30k_points];

scale = 1.2;

sx = -240;

sy = -240;

updateVis = function() {
  var i, j, k, m, ref, ref1, ref2, s, t, text, x, y;
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, 500, 500);
  ctx.fillStyle = "yellow";
  for (i = j = 0, ref = points[type].length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
    ref1 = points[type][i], x = ref1[0], y = ref1[1];
    ctx.fillRect(x * scale + 250 + sx, -y * scale + 250 + sy, 1, 1);
  }
  text = document.getElementById("area").value;
  text = text.split("\n").join(" ").split(" ");
  m = Math.floor(text.length / 2);
  ctx.strokeStyle = "white";
  for (i = k = 0, ref2 = m; 0 <= ref2 ? k < ref2 : k > ref2; i = 0 <= ref2 ? ++k : --k) {
    s = text[2 * i] ^ 0;
    t = text[2 * i + 1] ^ 0;
    if (s >= n || t >= n) {
      alert("Error");
      return;
    }
    ctx.beginPath();
    ctx.moveTo(points[type][s][0] * scale + 250 + sx, -points[type][s][1] * scale + 250 + sy);
    ctx.lineTo(points[type][t][0] * scale + 250 + sx, -points[type][t][1] * scale + 250 + sy);
    ctx.stroke();
  }
};

setScale = function(sc) {
  scale = sc;
  return updateVis();
};

rescale = function() {
  return setScale(+document.getElementById("scale").value);
};
